name: cli-test
cloud_provider: gcp

services:
  airflow:
    name: airflow
    type: airflow
    version: 0.1
    containers:
      webserver: 1
      # scheduler: 1
      # worker: 2
      # flower: 1
      postgres: 1
      # redis: 1
  # stocks:
  #   type: postgres

gcp:
  project_id: ab-cli-test
  zone: us-central1-a
  service_account_key_path: ../keys/phidata-sa-pk.json
  gke:
    name: cli-test-cluster
    version: 1.15.9-gke.22
    use_ip_aliases: True
    node_pools:
      - name: cli-test-cluster-np
        min_node_count: 1
        max_node_count: 5
  # gcs:
  #   buckets:
  #     - "cli-test-bucket"
  # cloudsql:
  #   instances:
  #     - "phi-db"

k8s:
  namespace: cli-test-ns
  context: cli-test-ctx
